add server `status` as an option to filter the server inventory list
ansible-collections/hetzner.hcloud pull request #126
Opened 2022-04-12 09:08 UTC by tagirb

##### SUMMARY
It is quite often required to only include the `running` servers in the Ansible dynamic inventory. While it is possible to create `keyed_groups` for that purpose, having an option to filter out the servers with a different status directly in the plugin configuration in the same way as with `locations`, `types`, and `networks` looks simple and attractive.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Inventory Plugin

2022-06-09 13:00 UTC, LKaemmerling requested changes

2022-06-09 13:00 UTC, LKaemmerling commented on plugins/inventory/hcloud.py
> +          type: list
This should fix the sanity check :)
```suggestion
          type: list
          elements: str

2022-06-13 06:52 UTC, tagirb commented
@LKaemmerling thank you for reviewing my contribution and suggesting the fix! I've commited your proposed change. The pipeline has two failed jobs, but it seems they failed due to an unrelated reason. Could you please try rerunning them both?

2022-06-13 06:54 UTC, LKaemmerling commented
Hey @tagirb,

yep they are unrelated. Thank you! We will merge this soonish

2022-06-13 06:57 UTC, merged