Inventory plugin: Allow token to be provided through extra-vars.
ansible-collections/hetzner.hcloud pull request #156
Opened 2022-09-30 12:03 UTC by n00b42

##### SUMMARY
Allow token to be provided through extra-vars.
Allows "dynamic" insertion of the token without changing the environment variables

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
hetzner.hcloud.hcloud

##### ADDITIONAL INFORMATION
Only thing I am not perfectly sure about is, if one can safely use `self._compose` and `self._compose` in a custom plugin.

2023-01-27 12:10 UTC, apricote commented
Hey @n00b42, thanks for the contribution!

This fails for me with the nested extra var:

```
[WARNING]:  * Failed to parse ./hcloud.yaml with auto plugin: 'hetzner' is undefined
```

It works if I use `hetzner_apitoken` instead (or any other value that does not use a dot)

2023-01-27 12:14 UTC, apricote requested changes
We already support templating logic when evaluating `token`. What is missing from that, is that the extra vars are not passed to `self.templar.template`. `self._compose()` under the hood passes those variables and then calls `self.templar.template`.

To avoid templating twice with nearly the same logic, what do you think about adding the `self._vars` to our templar instance?

```python
self.templar.available_variables = self._vars
self.api_token = self.templar.template(self.get_option("token"), fail_on_undefined=False) or os.getenv(self.token_env)
```

Then you can use the (extra) vars in the normal `token` templating:

```yaml
token: "{{ hcloud_token }}"
```

2023-01-27 14:43 UTC, n00b42 commented
I am fine with that as well, just needed a way to pass it using a variable.
Should I update the PR or will you do the changes yourself?

2023-01-27 14:46 UTC, apricote commented
> I am fine with that as well, just needed a way to pass it using a variable. Should I update the PR or will you do the changes yourself?

It would be great if you can update the PR, but I can also do it if you have no time.

2023-01-30 08:44 UTC, n00b42 commented
changed as suggested.

2023-01-30 09:42 UTC, apricote approved these changes

2023-01-30 11:08 UTC, merged